### ISSUE TITLE
Really bad spelling (agina)

### ISSUE THREAD

**Issue by dfalster** [stephquail/trial#1]
see [analysis.R](https://github.com/stephquail/trial/blob/master/analysis.R#L5)

**Comment by dfalster** [comment]
@stephquail can you tackle this?

**Comment by stephquail** [comment]
@dfalster NO :(

**Comment by dfalster** [comment]
Ok i've got it.

**Comment by dfalster** [comment]
Fixed in 24dcb8a6717474e27d1e9bbf3008c5d38b3cb75e
